export const allSymptoms = [
  "Fever",
  "Chills",
  "Cough",
  "Fatigue",
  "Loss of Smell",
  "Loss of Taste",
  "Headache",
  "Sore Throat",
  "Runny Nose",
  "Shortness of Breath",
  "Muscle Pain",
  "Joint Pain",
  "Diarrhea",
  "Nausea",
  "Vomiting",
  "Abdominal Pain",
  "Chest Pain",
  "Dizziness",
  "Confusion",
  "Rash",
  "Sneezing",
  "Eye Redness",
  "Itchy Eyes",
  "Nasal Congestion",
  "Difficulty Breathing",
  "Wheezing",
  "Bluish Lips or Face",
  "Swollen Lymph Nodes",
  "Excessive Sweating",
  "Loss of Appetite",
  "Tremors",
  "Tingling Sensations",
  "Skin Discoloration",
  "Palpitations",
  "Increased Heart Rate",
  "Low Blood Pressure",
  "High Blood Pressure",
  "Blurred Vision",
  "Light Sensitivity",
  "Hearing Loss",
  "Ear Pain",
  "Dry Mouth",
  "Dry Cough",
  "Productive Cough",
  "Night Sweats",
  "Frequent Urination",
  "Burning During Urination",
  "Blood in Stool",
  "Constipation",
  "Back Pain",
  "Neck Pain",
  "Difficulty Swallowing",
  "Swollen Hands or Feet",
  "Cold Extremities",
  "Fainting",
  "Mood Changes",
  "Irritability",
  "Depression",
  "Anxiety",
  "Memory Loss",
  "Delirium",
  "Seizures",
  "Yellowing of Skin or Eyes (Jaundice)",
  "Dry Skin",
  "Peeling Skin",
  "Mouth Ulcers",
  "Nosebleeds",
  "Hoarseness",
];
