import { faker } from "@faker-js/faker";
import client from "./db";

type Gender = "male" | "female" | "other";
type Vaccination = "yes" | "no" | "not sure";

export const countries: string[] = [
  "Afghanistan",
  "Angola",
  "Albania",
  "United Arab Emirates",
  "Argentina",
  "Armenia",
  "French Southern Territories",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Burundi",
  "Belgium",
  "Benin",
  "Burkina Faso",
  "Bangladesh",
  "Bulgaria",
  "Bahamas",
  "Bosnia and Herzegovina",
  "Belarus",
  "Belize",
  "Bolivia",
  "Brazil",
  "Brunei",
  "Bhutan",
  "Botswana",
  "Central African Republic",
  "Canada",
  "Switzerland",
  "Chile",
  "China",
  "Cote d'Ivoire",
  "Cameroon",
  "Democratic Republic of Congo",
  "Congo",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Germany",
  "Djibouti",
  "Denmark",
  "Greenland",
  "Dominican Republic",
  "Algeria",
  "Ecuador",
  "Egypt",
  "Eritrea",
  "Spain",
  "Estonia",
  "Ethiopia",
  "Finland",
  "Fiji",
  "France",
  "French Guiana",
  "Gabon",
  "United Kingdom",
  "Georgia",
  "Ghana",
  "Guinea",
  "Gambia",
  "Guinea-Bissau",
  "Equatorial Guinea",
  "Greece",
  "Guatemala",
  "Guyana",
  "Honduras",
  "Croatia",
  "Haiti",
  "Hungary",
  "Indonesia",
  "India",
  "Ireland",
  "Iran",
  "Iraq",
  "Iceland",
  "Israel",
  "Italy",
  "Jamaica",
  "Jordan",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Kyrgyzstan",
  "Cambodia",
  "South Korea",
  "Kosovo",
  "Kuwait",
  "Laos",
  "Lebanon",
  "Liberia",
  "Libya",
  "Sri Lanka",
  "Lesotho",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Morocco",
  "Moldova",
  "Madagascar",
  "Mexico",
  "North Macedonia",
  "Mali",
  "Myanmar",
  "Montenegro",
  "Mongolia",
  "Mozambique",
  "Mauritania",
  "Malawi",
  "Malaysia",
  "Namibia",
  "New Caledonia",
  "Niger",
  "Nigeria",
  "Nicaragua",
  "Netherlands",
  "Norway",
  "Nepal",
  "New Zealand",
  "Oman",
  "Pakistan",
  "Panama",
  "Peru",
  "Philippines",
  "Papua New Guinea",
  "Poland",
  "Puerto Rico",
  "North Korea",
  "Portugal",
  "Paraguay",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Western Sahara",
  "Saudi Arabia",
  "Sudan",
  "South Sudan",
  "Senegal",
  "Solomon Islands",
  "Sierra Leone",
  "El Salvador",
  "Somalia",
  "Serbia",
  "Suriname",
  "Slovakia",
  "Slovenia",
  "Sweden",
  "Eswatini",
  "Syria",
  "Chad",
  "Togo",
  "Thailand",
  "Tajikistan",
  "Turkmenistan",
  "Timor",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Taiwan",
  "Tanzania",
  "Uganda",
  "Ukraine",
  "Uruguay",
  "United States",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Vanuatu",
  "West Bank",
  "Yemen",
  "South Africa",
  "Zambia",
  "Zimbabwe",
  "Cape Verde",
  "Comoros",
  "Mauritius",
  "Seychelles",
  "Bahrain",
  "Maldives",
  "Marshall Islands",
  "Micronesia (country)",
  "Nauru",
  "Palau",
  "Samoa",
  "Singapore",
  "Tonga",
  "Tuvalu",
  "Antigua and Barbuda",
  "Barbados",
  "Dominica",
  "Grenada",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Andorra",
  "Liechtenstein",
  "Malta",
  "Monaco",
  "San Marino",
  "Kiribati",
  "Sao Tome and Principe",
];

export const allSymptoms = [
  "Fever",
  "Chills",
  "Cough",
  "Fatigue",
  "Loss of Smell",
  "Loss of Taste",
  "Headache",
  "Sore Throat",
  "Runny Nose",
  "Shortness of Breath",
  "Muscle Pain",
  "Joint Pain",
  "Diarrhea",
  "Nausea",
  "Vomiting",
  "Abdominal Pain",
  "Chest Pain",
  "Dizziness",
  "Confusion",
  "Rash",
  "Sneezing",
  "Eye Redness",
  "Itchy Eyes",
  "Nasal Congestion",
  "Difficulty Breathing",
  "Wheezing",
  "Bluish Lips or Face",
  "Swollen Lymph Nodes",
  "Excessive Sweating",
  "Loss of Appetite",
  "Tremors",
  "Tingling Sensations",
  "Skin Discoloration",
  "Palpitations",
  "Increased Heart Rate",
  "Low Blood Pressure",
  "High Blood Pressure",
  "Blurred Vision",
  "Light Sensitivity",
  "Hearing Loss",
  "Ear Pain",
  "Dry Mouth",
  "Dry Cough",
  "Productive Cough",
  "Night Sweats",
  "Frequent Urination",
  "Burning During Urination",
  "Blood in Stool",
  "Constipation",
  "Back Pain",
  "Neck Pain",
  "Difficulty Swallowing",
  "Swollen Hands or Feet",
  "Cold Extremities",
  "Fainting",
  "Mood Changes",
  "Irritability",
  "Depression",
  "Anxiety",
  "Memory Loss",
  "Delirium",
  "Seizures",
  "Yellowing of Skin or Eyes (Jaundice)",
  "Dry Skin",
  "Peeling Skin",
  "Mouth Ulcers",
  "Nosebleeds",
  "Hoarseness",
];

function generateRandomUser() {
  const gender: Gender = faker.helpers.arrayElement([
    "male",
    "female",
    "other",
  ]);
  const name = faker.person.firstName(gender === "male" ? "male" : "female");
  const surname = faker.person.lastName();
  const city = faker.location.city();
  const country = faker.helpers.arrayElement(countries);
  const age = faker.number.int({ min: 1, max: 100 });
  const contact = faker.internet.email({ firstName: name, lastName: surname });
  const symptoms = faker.helpers.arrayElements(
    allSymptoms,
    faker.number.int({ min: 1, max: 5 })
  );
  const vaccination: Vaccination = faker.helpers.arrayElement([
    "yes",
    "no",
    "not sure",
  ]);
  const additional_info = "fake user data";
  const rawDate = faker.date.recent({ days: 360 });
  const created_at = rawDate.toISOString().replace("T", " ").replace("Z", "");

  return {
    user_id: 1,
    name,
    surname,
    city,
    country,
    age,
    gender,
    contact,
    symptoms,
    vaccination,
    additional_info,
    created_at,
  };
}

export async function insertFakeUsers(count: number) {
  for (let i = 0; i < count; i++) {
    const user = generateRandomUser();

    await client.query(
      `INSERT INTO survey
      (user_id, name, surname, city, country, age, gender, contact, symptoms, vaccination, additional_info, created_at)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,
      [
        user.user_id,
        user.name,
        user.surname,
        user.city,
        user.country,
        user.age,
        user.gender,
        user.contact,
        user.symptoms,
        user.vaccination,
        user.additional_info,
        user.created_at,
      ]
    );
  }

  console.log(`${count} losowych rekordów zostało dodanych.`);
}
